name: Training Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'pipelines/**'
      - '.github/workflows/training.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'pipelines/**'
      - '.github/workflows/training.yml'

jobs:
  train:
    runs-on: ubuntu-latest
    
    env:
      MLFLOW_TRACKING_URI: http://localhost:5000
      KERAS_BACKEND: jax
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -c "from pipelines.common import PACKAGES; print(f'pip install metaflow=={PACKAGES[\"metaflow\"]} mlflow=={PACKAGES[\"mlflow\"]} python-dotenv=={PACKAGES[\"python-dotenv\"]}')" | bash
          pip install pylint==3.3.1

      - name: Start MLflow server
        run: |
          mlflow server --host 0.0.0.0 --port 5000 &
          sleep 5  # Wait for server to start

      - name: Run training pipeline
        run: python pipelines/training.py --environment=pypi run