name: Training Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'pipelines/**'
      - '.github/workflows/training.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'pipelines/**'
      - '.github/workflows/training.yml'

jobs:
  train:
    runs-on: ubuntu-latest
    
    env:
      MLFLOW_TRACKING_URI: http://localhost:5000
      KERAS_BACKEND: jax
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install metaflow mlflow python-dotenv

      - name: Run training pipeline
        run: python pipelines/training.py --environment=pypi run